articles/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "articles"
urlpatterns = [
    path("create/", views.CreateArticle, name="create"),
    path("", views.ArticleList, name="list"),
    path('<slug>', views.DetailArticle, name="detail"),

]

madcraftProject/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


urlpatterns = [
    path('admin/', admin.site.urls),
    path("", views.Home, name="home"),
    path("users/", include("users.urls")),
    path('articles/', include('articles.urls')),
    path('about/', views.About, name="about" )
]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "users"
urlpatterns = [
    path("signup/", views.signup_view, name="signup"),
    path('logout/', views.logout_view, name="logout"),
    path('dashboard/', views.dashboard_view, name="dashboard"),
    path('dashboard/detail/', views.UserDetail, name="detail"),
    path('changeemail/', views.ChangeEmail_view, name="changeEmail"),
    path('changepassword/', views.ChangePassword_view, name="changePassword"),
    path("login/", views.login_view, name="login"),
]

articles/models.py
from django.db import models
from django.contrib.auth.models import User


class Article(models.Model):
    title = models.CharField(max_length=120)
    body = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    slug = models.SlugField()
    thumbnail = models.ImageField(default="default-image.jpg", blank=True)
    author = models.ForeignKey(User, default=None, on_delete=models.CASCADE)
    description = models.CharField(max_length=150)
    show = models.BooleanField(default=False)

    def __str__(self):
        return self.title


class Comments(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    active = models.BooleanField(default=False)

    class Meta:
        ordering = ['date']

    def __str__(self):
        return f'comment {self.body} by {self.name}'

users/models.py
from django.db import models
from django.contrib.auth.models import User

articles/forms.py
from django import forms
from . import models


class CreateNewArticle(forms.ModelForm):
    class Meta:
        model = models.Article
        fields = ["title", "slug", "body", "thumbnail", "description"]


class CommentForm(forms.ModelForm):
    class Meta:
        model = models.Comments
        fields = ('name', "email", "body")

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from . import models


class RegisterForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2")


class ChangeEmail(forms.Form):
    email = forms.CharField(required=True, max_length=120, widget=forms.TextInput(attrs={'name': 'emailInput'}))


class ChangePassword(forms.Form):
    oldPassword = forms.CharField(required=True, min_length=8, max_length=80, widget=forms.PasswordInput(attrs={'name':"oldPassword"}))
    password1 = forms.CharField(required=True, min_length=8, max_length=80, widget=forms.PasswordInput(attrs={'name': 'password1'}), label="Password")
    password2 = forms.CharField(required=True, min_length=8, max_length=80, widget=forms.PasswordInput(attrs={'name': 'password2'}), label='Confirm password')

articles/views.py
from django.shortcuts import render, redirect
from . import forms
from django.contrib.auth.decorators import login_required
from . import models


@login_required(login_url="/users/login")
def CreateArticle(request):
    if request.method == "POST":
        form = forms.CreateNewArticle(request.POST, request.FILES)
        if form.is_valid():
            formInstance = form.save(commit=False)
            formInstance.author = request.user
            formInstance.save()
            return redirect("home")

    form = forms.CreateNewArticle
    return render(request, 'articles/createArticle.html', {"form": form})


def DetailArticle(request, slug):
    article = models.Article.objects.get(slug=slug)

    commentShow = models.Comments.objects.all()
    if request.method == "POST":
        comment = forms.CommentForm(request.POST or None)
        if comment.is_valid():
            comment = comment.save(commit=False)
            comment.article_id = article.id
            comment.save()
            return redirect(request.path)

    comment = forms.CommentForm()
    return render(request, 'articles/detail.html', {"article": article, "commentForm": comment, "comments": commentShow})


def ArticleList(request):
    articles = models.Article.objects.all().order_by('-date')
    return render(request, 'articles/list.html', {"articles":articles})

madcraftProject/views.py
from django.shortcuts import render
from articles import models


def Home(request):
    articles = models.Article.objects.all().order_by('-date')
    return render(request, "home.html", {'articles': articles})


def About(request):
    return render(request, "about.html")

users/views.py
from django.shortcuts import render, redirect, HttpResponse
from django.contrib.auth.forms import UserCreationForm
from .forms import RegisterForm, ChangeEmail, ChangePassword
from django.contrib.auth import login, logout
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required


def signup_view(request):
    if request.method == "POST":
        form = RegisterForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect("home")
    else:
        form = RegisterForm()
    return render(request, "users/sign_up.html", {"form": form})


def logout_view(request):
    if request.method == "POST":
        logout(request)
        return redirect('home')
    else:
        return redirect('home')


@login_required(login_url='/users/login/')
def dashboard_view(request):
    return render(request, 'users/dashboard.html')


@login_required(login_url='/users/login/')
def UserDetail(request):

    user = request.user
    return render(request, "users/userDetail.html", {'user': user})


@login_required(login_url='/users/login/')
def ChangeEmail_view(request):
    user = User.objects.get(username=request.user.username)
    if request.method == "POST":
        changeEmailForm = ChangeEmail(request.POST)
        if changeEmailForm.is_valid():
            if user.email != changeEmailForm['email'].value():
                user.email = changeEmailForm['email'].value()
                user.save()
                return redirect('users:detail')
    changeEmailForm = ChangeEmail()
    return render(request, 'users/changeEmail.html', {'changeEmailForm':changeEmailForm})


@login_required(login_url="/users/login/")
def ChangePassword_view(request):
    user = User.objects.get(username=request.user.username)
    if request.method == "POST":
        passwordForm = ChangePassword(request.POST)
        if passwordForm.is_valid():
            if user.check_password(passwordForm['oldPassword']):
                if passwordForm['oldPassword'] != passwordForm['password1']:
                    if passwordForm['password1'].value() == passwordForm['password2'].value():
                        user.set_password(passwordForm['password1'].value())
                        user.save()
                        return redirect('users:detail')

    passwordForm = ChangePassword()
    return render(request, 'users/changePassword.html', {'passwordForm': passwordForm})


def login_view(request):
    if request.method == "POST":
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            if "next" in request.POST:
                return redirect(request.POST.get("next"))
            else:
                return redirect("home")
    else:
        form = AuthenticationForm()
    return render(request, "users/login.html", {"form": form})

templates/about.html
{% extends 'base.html' %}

{% block title %}{% endblock %}


{% block body %}

    <h1>about</h1>
{% endblock %}

templates/articles/createArticle.html
{% extends 'base.html' %}


{% block title %}Writing{% endblock %}
{% block body %}
    <h1>create your article</h1>
    <form action="{% url 'articles:create' %}" method="post" id="createArticle" enctype="multipart/form-data">

    {% csrf_token %}
    {{ form }}
    <button type="submit">Create</button>
    </form>
{% endblock %}

templates/articles/detail.html
{% extends 'base.html' %}
{% load static %}

{% block title %}articles{% endblock %}

{% block body %}

    <img src="/media/{{ article.thumbnail }}" alt="عکس لود نشد" id="thumbnail">
    <h2>{{ article.title }}</h2>
    <p>Writing by : {{ article.author }}</p>
    <p>{{ article.date }}</p>
    <p>{{ article.body }}</p>

    <form action="" method="post" id="comment_form">
    {{ commentForm }}
    {% csrf_token %}
    <button class="button">Send</button>
    </form>

    {% for comment in comments %}
        {% if article.id == comment.article_id and comment.active %}
        <p>{{ comment.name }}</p>
        <p>{{ comment.date }}</p>
        <p>{{ comment.body }}</p>
        {% endif %}
    {% endfor %}
{% endblock %}

templates/articles/list.html
{% extends 'base.html' %}

{% block title %}Articles{% endblock %}

{% block body %}

    {% for article in articles %}
        {% if article.show == True %}
    <div class="article">
    <img src="/media/{{ article.thumbnail }}" alt="عکس لود نشد" class="article_image">
    <h3><a href="{{ article.slug }}">{{ article.title }}</a></h3>
    <p>{{ article.description }}</p>
    </div>
        {% endif %}
    {% endfor %}

{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    {% block header %}{% endblock %}
    <meta charset="UTF-8">
    <script src="https://kit.fontawesome.com/154bbbe058.js" crossorigin="anonymous"></script>
    <title>
    {% block title %}
    {% endblock %}
    </title>

    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>

<div id="content">
<div id="menus">
    <ul class="horizontal">
      <li>
          <a class="active" href="{% url 'home' %}">Home</i></a>
      </li>
      <li>
          <a href="{% url 'articles:list' %}">Article</a>
      </li>
      <li>
          <a href="{% url 'about' %}">About</a>
      </li>
      {% if user.is_authenticated %}
          <a href="{% url 'users:dashboard' %}" id="logoIcon"><img src="/media/298756-512.png" alt="DASHBOARD"></a>
       <a href="{% url 'articles:create' %}">Writing Article</a>
          <form action="{% url 'users:logout' %}" method="post" id="logout_button">
          <button type="submit">Logout</button>
          {% csrf_token %}
          </form>
      {% else %}
      <a href="{% url 'users:login' %}">Login</a>
      <a href="{% url 'users:signup' %}">Signup</a>
      {% endif %}

    </ul>

</div>
{% block body %}
{% endblock %}
</div>
</body>
</html>

templates/home.html
<div id="home-background">
{% extends 'base.html' %}
{% load static %}

{% block header %}
    <link rel="stylesheet" href="{% static 'home.css' %}">
{% endblock %}

{% block title %}HOME{% endblock %}


{% block body %}

    <div id="back-parent">
        <div id="back">
            <header>
                <div id="header">
                    <div id="bio-python-box" class="bio position-in-back">
                        <h1>python</h1>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dignissimos eaque explicabo laborum. Ad consequatur deleniti dolores labore laboriosam natus non nostrum obcaecati, qui voluptas? Illo labore magnam magni reiciendis sint.</p>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dignissimos eaque explicabo laborum. Ad consequatur deleniti dolores labore laboriosam natus non nostrum obcaecati, qui voluptas? Illo labore magnam magni reiciendis sint.</p>
                    </div>
                    <div id="bio-sit-box" class="bio position-in-back">
                        <h1>python site</h1>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Cum cumque eaque facilis libero magni quo sunt velit, voluptatem? Accusamus debitis, delectus laboriosam magnam mollitia odit officia repudiandae soluta ullam voluptatem.</p>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Cum cumque eaque facilis libero magni quo sunt velit, voluptatem? Accusamus debitis, delectus laboriosam magnam mollitia odit officia repudiandae soluta ullam voluptatem.</p>
                    </div>
                </div>
            </header>


        <div id="content">

            {% for article in articles %}

                {% if article.show %}
                    <div class="articlesBox">
                    <a href="/articles/{{ article.slug }}"><img src="/media/{{ article.thumbnail }}" alt="image" class="articlesImage"></a>
                    <h3 class="articlesTitle"><a href="/articles/{{ article.slug }}">{{ article.title }}</a></h3>
                    <p class="articlesDate">{{ article.date }}</p>
                    <p class="articlesDescription">{{ article.description }}</p>
                    <a href="#" class="articlesAuthor">Writing by : {{ article.author }}</a>
                    </div>
                {% endif %}

            {% endfor %}

    </div>


        </div>
    </div>


{% endblock %}
</div>

templates/users/changeEmail.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <meta charset="UTF-8">
    <title>change email</title>
</head>
<body>

<form method="post" class="ChangeEmailForm" action="{% url 'users:changeEmail' %}">
    {{ changeEmailForm }}
    {% csrf_token %}
    <button type="submit">Change</button>
</form>

</body>
</html>

templates/users/changePassword.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>change password</title>
</head>
<body>

<form action="{% url 'users:changePassword'%}" method="post" class="changePasswordForm">

    {{ passwordForm }}
    {% csrf_token %}
    <button type="submit">change</button>

</form>

</body>
</html>

templates/users/dashboard.html
{% load  static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'dashboard.css' %}">

</head>
<body>
{#    <div><a href="{% url 'home' %}">Home</a></div>#}
{#    <div><a href="{% url 'users:detail' %}">my details</a></div>#}
{#    <div><a href="{% url 'articles:create' %}">Writing article</a></div>#}
    <script src="{% static 'dashboard.js' %}"></script>


<svg style="display:none;">
  <symbol id="down" viewBox="0 0 16 16">
    <polygon points="3.81 4.38 8 8.57 12.19 4.38 13.71 5.91 8 11.62 2.29 5.91 3.81 4.38" />
  </symbol>
  <symbol id="users" viewBox="0 0 16 16">
    <path d="M8,0a8,8,0,1,0,8,8A8,8,0,0,0,8,0ZM8,15a7,7,0,0,1-5.19-2.32,2.71,2.71,0,0,1,1.7-1,13.11,13.11,0,0,0,1.29-.28,2.32,2.32,0,0,0,.94-.34,1.17,1.17,0,0,0-.27-.7h0A3.61,3.61,0,0,1,5.15,7.49,3.18,3.18,0,0,1,8,4.07a3.18,3.18,0,0,1,2.86,3.42,3.6,3.6,0,0,1-1.32,2.88h0a1.13,1.13,0,0,0-.27.69,2.68,2.68,0,0,0,.93.31,10.81,10.81,0,0,0,1.28.23,2.63,2.63,0,0,1,1.78,1A7,7,0,0,1,8,15Z" />
  </symbol>
  <symbol id="collection" viewBox="0 0 16 16">
    <rect width="7" height="7" />
    <rect y="9" width="7" height="7" />
    <rect x="9" width="7" height="7" />
    <rect x="9" y="9" width="7" height="7" />
  </symbol>
  <symbol id="comments" viewBox="0 0 16 16">
    <path d="M0,16.13V2H15V13H5.24ZM1,3V14.37L5,12h9V3Z" />
    <rect x="3" y="5" width="9" height="1" />
    <rect x="3" y="7" width="7" height="1" />
    <rect x="3" y="9" width="5" height="1" />
  </symbol>
  <symbol id="pages" viewBox="0 0 16 16">
    <rect x="4" width="12" height="12" transform="translate(20 12) rotate(-180)" />
    <polygon points="2 14 2 2 0 2 0 14 0 16 2 16 14 16 14 14 2 14" />
  </symbol>
  </symbol>
  <symbol id="collapse" viewBox="0 0 16 16">
    <polygon points="11.62 3.81 7.43 8 11.62 12.19 10.09 13.71 4.38 8 10.09 2.29 11.62 3.81" />
  </symbol>
  <symbol id="search" viewBox="0 0 16 16">
    <path d="M6.57,1A5.57,5.57,0,1,1,1,6.57,5.57,5.57,0,0,1,6.57,1m0-1a6.57,6.57,0,1,0,6.57,6.57A6.57,6.57,0,0,0,6.57,0Z" />
    <rect x="11.84" y="9.87" width="2" height="5.93" transform="translate(-5.32 12.84) rotate(-45)" />
  </symbol>
</svg>
<header class="page-header">
  <nav>
    <button class="toggle-mob-menu" aria-expanded="false" aria-label="open menu">
      <svg width="20" height="20" aria-hidden="true">
        <use xlink:href="#down"></use>
      </svg>
    </button>
    <ul class="admin-menu">
      <li class="menu-heading">
      </li>
      <li>
        <a href="{% url 'home' %}">
          <svg>
            <use xlink:href="#collection"></use>
          </svg>
          <span>Home</span>
        </a>
      </li>
      <li>
        <a href="{% url 'users:detail' %}">
          <svg>
            <use xlink:href="#users"></use>
          </svg>
          <span>My details</span>
        </a>
      </li>
      <li>
        <a  href="{% url 'articles:create' %}">
          <svg>
            <use xlink:href="#comments"></use>
          </svg>
          <span>Writing article</span>
        </a>
      </li>
      <li>
        <a href="#0">
          <svg>
            <use xlink:href="#collapse"></use>
          </svg>
          <form action="{% url 'users:logout' %}" method="post" id="logout_button_dashboard">
          <button type="submit">Logout</button>
          {% csrf_token %}
          </form>
        </a>
      </li>
  </nav>
</header>
<section class="page-content">
  <section class="grid">
    <article></article>
    <article></article>
    <article></article>
    <article></article>
    <article></article>
    <article></article>
    <article></article>
    <article></article>
  </section>
</section>


</body>
</html>

templates/users/login.html
<div id="background-login">
{% extends 'base.html' %}

{% block title %}login{% endblock %}

{% block body %}
    <div id="parent-login-box">
        <div id="login-box">
            <h1 id="login">LOGIN</h1>
            <form action="{% url 'users:login'%}" class="form_logandsing" method="post" style="
                text-align: left;">

            {% csrf_token %}
            {{ form }}
            <button type="submit" id="button_login">LOGIN</button>

            </form>
        </div>
    </div>

{% endblock %}
 </div>

templates/users/sign_up.html
<div id="background-login">
{% extends 'base.html' %}

{% block title %}SIGNUP{% endblock %}

{% block body %}
     <div id="parent-login-box">
        <div id="login-box">
            <h1 id="login">SIGNUP</h1>
            <br>
            <br>
            <br>
            <br>
            <br>

                <form action="{% url 'users:signup' %}" method="post" class="form_logandsing">
                {% csrf_token %}
                {{ form }}
                <button type="submit" id="button">SIGNUP</button>
                </form>
        </div>
    </div>
{% endblock %}
</div>

templates/users/userDetail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>my details</title>
</head>
<body>
<label>
    username:
    <input type="text" value="{{ user.username }}" disabled="disabled">
</label>
<label>
    email:
    {% if user.email == "" %}
    <input type="email" placeholder="You do not have email" disabled="disabled">
    {% else %}
    <input type="email" value="{{ user.email }}" disabled="disabled">
    {% endif %}
</label>

<a href="{% url 'users:changeEmail' %}">change email</a>
<a href="{% url 'users:changePassword' %}">change Password</a>

</body>
</html>